

whenever sqlerror exit rollback;
-- PERMISOS REFERENCES PARA LOS MODULOS
GRANT REFERENCES ON TABLA CLIENTE_USR.SESION TO GIMNASIO_USR;
GRANT REFERENCES ON TABLA CLIENTE_USR.SESION_SENSOR TO GIMNASIO_USR;
GRANT REFERENCES ON TABLA CLIENTE_USR.CLIENTE_GIMNASIO TO GIMNASIO_USR;

-- 
-- TABLE: ADMINISTRADOR 
--

ALTER TABLE GIMNASIO_USR.ADMINISTRADOR ADD CONSTRAINT ADMINISTRADOR_EMPLEADO_ID_FK
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES GIMNASIO_USR.EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: APARATO 
--

ALTER TABLE GIMNASIO_USR.APARATO ADD CONSTRAINT APARATO_TIPO_DISPOSITIVO_ID_FK 
    FOREIGN KEY (TIPO_DISPOSITIVO_ID)
    REFERENCES GIMNASIO_USR.TIPO_APARATO(TIPO_DISPOSITIVO_ID)
;

ALTER TABLE GIMNASIO_USR.APARATO ADD CONSTRAINT APARATO_STATUS_ID_FK 
    FOREIGN KEY (STATUS_ID)
    REFERENCES GIMNASIO_USR.STATUS_APARATO(STATUS_ID)
;

ALTER TABLE GIMNASIO_USR.APARATO ADD CONSTRAINT APARATO_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES GIMNASIO_USR.SALA(SALA_ID)
;


-- 
-- TABLE: BIOMETRICO 
--

ALTER TABLE GIMNASIO_USR.BIOMETRICO ADD CONSTRAINT BIOMETRICO_EMPLEADO_ID 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES GIMNASIO_USR.EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: CALORIAS_SESION 
--

ALTER TABLE CLIENTE_USR.CALORIAS_SESION ADD CONSTRAINT CALORIAS_SESION_CLIENTE_ID_NO_SESION_FK 
    FOREIGN KEY (CLIENTE_ID, NO_SESION)
    REFERENCES CLIENTE_USR.SESION(CLIENTE_ID, NO_SESION)
;


-- 
-- TABLE: CLIENTE_GIMNASIO 
--

ALTER TABLE CLIENTE_USR.CLIENTE_GIMNASIO ADD CONSTRAINT CLIENTE_GIMNASIO_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_USR.CLIENTE(CLIENTE_ID)
;
--***************************************************************************
ALTER TABLE CLIENTE_USR.CLIENTE_GIMNASIO ADD CONSTRAINT CLIENTE_GIMNASIO_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO_USR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: CREDENCIAL 
--

ALTER TABLE CLIENTE_USR.CREDENCIAL ADD CONSTRAINT CREDENCIAL_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_USR.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: DISCIPLINA_SALAS 
--

ALTER TABLE GIMNASIO_USR.DISCIPLINA_SALA ADD CONSTRAINT DISCIPLINA_SALA_DISCIPLINA_ID_FK 
    FOREIGN KEY (DISCIPLINA_ID)
    REFERENCES GIMNASIO_USR.DISCIPLINA(DISCIPLINA_ID)
;

ALTER TABLE GIMNASIO_USR.DISCIPLINA_SALA ADD CONSTRAINT DISCIPLINA_SALA_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES GIMNASIO_USR.SALA(SALA_ID)
;


-- 
-- TABLE: EMPLEADO 
--

ALTER TABLE GIMNASIO_USR.EMPLEADO ADD CONSTRAINT EMPLEADO_PUESTO_ID_FK 
    FOREIGN KEY (PUESTO_ID)
    REFERENCES GIMNASIO_USR.PUESTO(PUESTO_ID)
;


-- 
-- TABLE: GIMNASIO 
--

ALTER TABLE GIMNASIO_USR.GIMNASIO ADD CONSTRAINT GIMNASIO_GERENTE_FK 
    FOREIGN KEY (GERENTE)
    REFERENCES GIMNASIO_USR.ADMINISTRADOR(EMPLEADO_ID)
;


-- 
-- TABLE: INSTRUCTOR 
--

ALTER TABLE GIMNASIO_USR.INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES GIMNASIO_USR.EMPLEADO(EMPLEADO_ID)
;

ALTER TABLE GIMNASIO_USR.INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_SUPLENTE_FK 
    FOREIGN KEY (SUPLENTE)
    REFERENCES GIMNASIO_USR.INSTRUCTOR(EMPLEADO_ID)
;


-- 
-- TABLE: MEDIDA 
--

ALTER TABLE CLIENTE_USR.MEDIDA ADD CONSTRAINT MEDIDA_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_USR.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: MULTIMEDIA 
--

ALTER TABLE GIMNASIO_USR.MULTIMEDIA ADD CONSTRAINT MULTIMEDIA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO_USR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: SALA 
--

ALTER TABLE GIMNASIO_USR.SALA ADD CONSTRAINT SALA_RESPONSABLE_FK 
    FOREIGN KEY (RESPONSABLE)
    REFERENCES GIMNASIO_USR.ADMINISTRADOR(EMPLEADO_ID)
;

ALTER TABLE GIMNASIO_USR.SALA ADD CONSTRAINT SALA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES GIMNASIO_USR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: SENSOR 
--

ALTER TABLE CLIENTE_USR.SENSOR ADD CONSTRAINT SENSOR_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_USR.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: SESION 
--
--******************************************************
ALTER TABLE CLIENTE_USR.SESION ADD CONSTRAINT SESION_INSTRUCTOR_FK 
    FOREIGN KEY (INSTRUCTOR)
    REFERENCES GIMNASIO_USR.INSTRUCTOR(EMPLEADO_ID)
;
--******************************************************
ALTER TABLE CLIENTE_USR.SESION ADD CONSTRAINT SESION_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES GIMNASIO_USR.SALA(SALA_ID)
;

ALTER TABLE CLIENTE_USR.SESION ADD CONSTRAINT SESION_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_USR.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: SESION_SENSOR 
--

ALTER TABLE CLIENTE_USR.SESION_SENSOR ADD CONSTRAINT SESION_SENSOR_APARATO_ID_FK 
    FOREIGN KEY (APARATO_ID)
    REFERENCES GIMNASIO_USR.APARATO(APARATO_ID)
;

ALTER TABLE CLIENTE_USR.SESION_SENSOR ADD CONSTRAINT SESION_SENSOR_CLIENTE_ID_NO_SESION_FK 
    FOREIGN KEY (CLIENTE_ID, NO_SESION)
    REFERENCES CLIENTE_USR.SESION(CLIENTE_ID, NO_SESION)
;


-- 
-- TABLE: STATUS_APARTO_HISTORICO 
--

ALTER TABLE GIMNASIO_USR.STATUS_APARATO_HISTORICO ADD CONSTRAINT STATUS_APARATO_HISTORICO_APARATO_ID_FK 
    FOREIGN KEY (APARATO_ID)
    REFERENCES GIMNASIO_USR.APARATO(APARATO_ID)
;

ALTER TABLE GIMNASIO_USR.STATUS_APARATO_HISTORICO ADD CONSTRAINT STATUS_APARATO_HISTORICO_STATUS_ID_FK 
    FOREIGN KEY (STATUS_ID)
    REFERENCES GIMNASIO_USR.STATUS_APARATO(STATUS_ID)
;


-- 
-- TABLE: URL_INSTRUCTOR 
--

ALTER TABLE GIMNASIO_USR.URL_INSTRUCTOR ADD CONSTRAINT URL_INSTRUCTOR_INSTRUCTOR_FK
    FOREIGN KEY (INSTRUCTOR)
    REFERENCES GIMNASIO_USR.INSTRUCTOR(EMPLEADO_ID)
;

