connect gimnasio_usr/gimnasio123;
--CARGA DE PUESTO
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (1,'ENTRENADOR PERSONAL','AKSHS','ENTRENA PERSONALMENTE A PERSONAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (2,'ENRTENADOR GRUPAL','ASKDO', 'ENTRENA A UN GRUPO DE PERSONAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (3,'RECEPCIONISTA','OWLFJ','RECIBE A LOS USUARIOS Y ATIENDE DUDAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (4,'IT','SOWND','RESUELVE PROBLEMAS DE SISTEMAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (5,'NUTRIOLOGO','PALEY','ALIMENTA A LAS PERSONAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (6,'MEDICO','SPQPD','SANA A LAS PERSONAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (7,'VENDEDOR','QOTDG','VENDE PRODUCTOS DEL GIMNASIO');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (8,'AGUADOR','SYQID','LE DA AGUA A LAS PERSONAS');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (9,'INSTRUCTOR DISCIPLINA','AYUDA','INSTRUYE ALGUNA DISCIPLINA');
insert into PUESTO (PUESTO_ID, NOMBRE, CLAVE, DESCRIPCION) values (10,'LIMPIEZA','RCYSJ','LIMPIA EL GIMNASIO');

-- CARGA DE TIPO_APARATO
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (1, 'MAQUINAS DE CARDIO' , 'CARDIO');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (2, 'MAQUINAS DE TREN SUPERIOR (PECHO/HOMBRO/ESPALDA)' , 'TREN SUPERIOR');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (3, 'MAQUINAS DE TREN INFERIOR (PIERNA)' , 'TREN INFERIOR');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (4, 'POLEAS DE DIFERENTES PESOS', 'POLEA');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (5, 'DISCOS DE PESO', 'PESO MUERTO');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (6, 'MAQUINAS DE RESISTENCIA', 'RESISTENCIA');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (7, 'DISPOSITIVOS AEROBICOS', 'AEROBICOS');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (8, 'BARRAS CON DIFERENTE FORMA', 'BARRAS');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (9, 'AGARRES PARA MANOS Y TOBILLOS', 'AGARRES');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (10, 'MANCUERNAS DE DIFERENTES PESOS', 'MANCUERNAS');
insert into TIPO_APARATO (TIPO_DISPOSITIVO_ID, DESCRIPCION, TIPO) values (11, 'MAQUINAS DE TREB MEDIO (ABS/ESPALDA BAJA)', 'TREN MEDIO');

-- CARGA DE DISCIPLINA
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (1, 'ALSNS', 'ALTEROFILIA', 'LEVANTAN BARRAS CON PESO', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (2, 'ALDKA', 'YOGA', 'ESTIRAMIENTOS Y RESPIRACION', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (3, 'RUXNA', 'CALISTENIA', 'EJERCICIOS CON SU CUERPO', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (4, 'AOEPA', 'PESAS', 'LEVANTAN PESAS', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (5, 'APDOS', 'TRX', 'JALAN CUERDAS', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (6, 'APSOA', 'ZUMBA', 'BAILAN Y SUDAN', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (7, 'PDOAL', 'CROSSFIT', 'EJERCICIOS RAPIDOS', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (8, 'OASLE', 'POWER JUMP', 'SALTAN', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (9, 'AOEKA', 'AEROBOX', 'BOXEAN CON EL AIRE', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (10, 'APSDL', 'SPINNING', 'SE SIENTAN A PEDALEAR EN BICICLETA', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (11, 'APDTH', 'STRETCHING', 'SE ESTIRAN MUCHO', empty_blob());
insert into DISCIPLINA (DISCIPLINA_ID, CLAVE, NOMBRE, DESCRIPCION, ICONO) values (12, 'WYFHS', 'PILATES', 'TERAPIAS DE REABILITACION', empty_blob());

-- CARGA DE STATUS_APARATO
insert into STATUS_APARATO (STATUS_ID, DESCRIPCION, STATUS) values (1, 'APARATO EN USO', 'VIGENTE');
insert into STATUS_APARATO (STATUS_ID, DESCRIPCION, STATUS) values (2, 'APARATO POR CAMBIAR', 'OBSOLETO');
insert into STATUS_APARATO (STATUS_ID, DESCRIPCION, STATUS) values (3, 'APARATO DESCOMPUESTO', 'AVERIADO');
insert into STATUS_APARATO (STATUS_ID, DESCRIPCION, STATUS) values (4, 'APARATO EN REPARACION', 'EN REPARACION');
insert into STATUS_APARATO (STATUS_ID, DESCRIPCION, STATUS) values (5, 'APARATO SIN USAR', 'FUERA DE USO');